# Generated by Django 3.2.4 on 2021-06-06 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeatherCollection',
            fields=[
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(default='', max_length=100)),
                ('current_temp', models.CharField(default='', max_length=100)),
                ('feels_like_temp', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'City Weather Collection',
                'verbose_name_plural': 'City Weather Collections',
                'db_table': 'city_weather_collection',
            },
        ),
        migrations.CreateModel(
            name='MailingTask',
            fields=[
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emails', jsonfield.fields.JSONField(default=list)),
                ('status', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mailing Task',
                'verbose_name_plural': 'Mailing Tasks',
                'db_table': 'mailing_task',
            },
        ),
    ]
