# Generated by Django 3.2.4 on 2021-06-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtask',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
